events { worker_connections 128; }
http {
  access_log off;
  client_max_body_size 32k;
  server {
    listen 8080;
    location = /render {
      proxy_pass http://renderer:8088/render;
      proxy_read_timeout 40s;
      proxy_set_header Authorization $http_authorization;
    }
    location / { return 404; }
  }
}
